// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/axhv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common Types
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_axhv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{0}
}

type VmIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmIdRequest) Reset() {
	*x = VmIdRequest{}
	mi := &file_proto_axhv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmIdRequest) ProtoMessage() {}

func (x *VmIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmIdRequest.ProtoReflect.Descriptor instead.
func (*VmIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{1}
}

func (x *VmIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VmId          string                 `protobuf:"bytes,3,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmResponse) Reset() {
	*x = VmResponse{}
	mi := &file_proto_axhv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmResponse) ProtoMessage() {}

func (x *VmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmResponse.ProtoReflect.Descriptor instead.
func (*VmResponse) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{2}
}

func (x *VmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VmResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// VM Creation
type CreateVmRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vcpu       uint32                 `protobuf:"varint,2,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	MemoryMib  uint32                 `protobuf:"varint,3,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	KernelPath string                 `protobuf:"bytes,4,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	// Use either rootfs_path OR template
	RootfsPath   string `protobuf:"bytes,5,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	Template     string `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty"`
	DiskSizeGb   uint32 `protobuf:"varint,7,opt,name=disk_size_gb,json=diskSizeGb,proto3" json:"disk_size_gb,omitempty"`
	GuestIp      string `protobuf:"bytes,8,opt,name=guest_ip,json=guestIp,proto3" json:"guest_ip,omitempty"`
	GuestGateway string `protobuf:"bytes,9,opt,name=guest_gateway,json=guestGateway,proto3" json:"guest_gateway,omitempty"`
	BootArgs     string `protobuf:"bytes,10,opt,name=boot_args,json=bootArgs,proto3" json:"boot_args,omitempty"`
	// Network Limits & Forwarding
	BandwidthLimitMbps uint32            `protobuf:"varint,11,opt,name=bandwidth_limit_mbps,json=bandwidthLimitMbps,proto3" json:"bandwidth_limit_mbps,omitempty"`
	PortMapTcp         map[string]uint32 `protobuf:"bytes,12,rep,name=port_map_tcp,json=portMapTcp,proto3" json:"port_map_tcp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // "external_port": internal_port
	PortMapUdp         map[string]uint32 `protobuf:"bytes,13,rep,name=port_map_udp,json=portMapUdp,proto3" json:"port_map_udp,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_proto_axhv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateVmRequest) GetVcpu() uint32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *CreateVmRequest) GetMemoryMib() uint32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *CreateVmRequest) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *CreateVmRequest) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *CreateVmRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CreateVmRequest) GetDiskSizeGb() uint32 {
	if x != nil {
		return x.DiskSizeGb
	}
	return 0
}

func (x *CreateVmRequest) GetGuestIp() string {
	if x != nil {
		return x.GuestIp
	}
	return ""
}

func (x *CreateVmRequest) GetGuestGateway() string {
	if x != nil {
		return x.GuestGateway
	}
	return ""
}

func (x *CreateVmRequest) GetBootArgs() string {
	if x != nil {
		return x.BootArgs
	}
	return ""
}

func (x *CreateVmRequest) GetBandwidthLimitMbps() uint32 {
	if x != nil {
		return x.BandwidthLimitMbps
	}
	return 0
}

func (x *CreateVmRequest) GetPortMapTcp() map[string]uint32 {
	if x != nil {
		return x.PortMapTcp
	}
	return nil
}

func (x *CreateVmRequest) GetPortMapUdp() map[string]uint32 {
	if x != nil {
		return x.PortMapUdp
	}
	return nil
}

// Disk Resize
type ResizeDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewSizeGb     uint32                 `protobuf:"varint,2,opt,name=new_size_gb,json=newSizeGb,proto3" json:"new_size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeDiskRequest) Reset() {
	*x = ResizeDiskRequest{}
	mi := &file_proto_axhv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeDiskRequest) ProtoMessage() {}

func (x *ResizeDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeDiskRequest.ProtoReflect.Descriptor instead.
func (*ResizeDiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{4}
}

func (x *ResizeDiskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResizeDiskRequest) GetNewSizeGb() uint32 {
	if x != nil {
		return x.NewSizeGb
	}
	return 0
}

// Listing
type ListVmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VmInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_proto_axhv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{5}
}

func (x *ListVmsResponse) GetVms() []*VmInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VmInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	SocketPath    string                 `protobuf:"bytes,3,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmInfo) Reset() {
	*x = VmInfo{}
	mi := &file_proto_axhv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmInfo) ProtoMessage() {}

func (x *VmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmInfo.ProtoReflect.Descriptor instead.
func (*VmInfo) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{6}
}

func (x *VmInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VmInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *VmInfo) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

// Stats
type VmStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuUsageUs         string                 `protobuf:"bytes,1,opt,name=cpu_usage_us,json=cpuUsageUs,proto3" json:"cpu_usage_us,omitempty"` // Microseconds
	MemoryUsedBytes    string                 `protobuf:"bytes,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	NetRxBytes         string                 `protobuf:"bytes,3,opt,name=net_rx_bytes,json=netRxBytes,proto3" json:"net_rx_bytes,omitempty"` // Upload (from VM perspective)
	NetTxBytes         string                 `protobuf:"bytes,4,opt,name=net_tx_bytes,json=netTxBytes,proto3" json:"net_tx_bytes,omitempty"` // Download (from VM perspective)
	DiskAllocatedBytes string                 `protobuf:"bytes,5,opt,name=disk_allocated_bytes,json=diskAllocatedBytes,proto3" json:"disk_allocated_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VmStatsResponse) Reset() {
	*x = VmStatsResponse{}
	mi := &file_proto_axhv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStatsResponse) ProtoMessage() {}

func (x *VmStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStatsResponse.ProtoReflect.Descriptor instead.
func (*VmStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{7}
}

func (x *VmStatsResponse) GetCpuUsageUs() string {
	if x != nil {
		return x.CpuUsageUs
	}
	return ""
}

func (x *VmStatsResponse) GetMemoryUsedBytes() string {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return ""
}

func (x *VmStatsResponse) GetNetRxBytes() string {
	if x != nil {
		return x.NetRxBytes
	}
	return ""
}

func (x *VmStatsResponse) GetNetTxBytes() string {
	if x != nil {
		return x.NetTxBytes
	}
	return ""
}

func (x *VmStatsResponse) GetDiskAllocatedBytes() string {
	if x != nil {
		return x.DiskAllocatedBytes
	}
	return ""
}

type HostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskTotalMib  uint64                 `protobuf:"varint,1,opt,name=disk_total_mib,json=diskTotalMib,proto3" json:"disk_total_mib,omitempty"`
	DiskUsedMib   uint64                 `protobuf:"varint,2,opt,name=disk_used_mib,json=diskUsedMib,proto3" json:"disk_used_mib,omitempty"`
	DiskFreeMib   uint64                 `protobuf:"varint,3,opt,name=disk_free_mib,json=diskFreeMib,proto3" json:"disk_free_mib,omitempty"`
	VmCount       uint32                 `protobuf:"varint,4,opt,name=vm_count,json=vmCount,proto3" json:"vm_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostStatsResponse) Reset() {
	*x = HostStatsResponse{}
	mi := &file_proto_axhv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostStatsResponse) ProtoMessage() {}

func (x *HostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axhv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostStatsResponse.ProtoReflect.Descriptor instead.
func (*HostStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_axhv_proto_rawDescGZIP(), []int{8}
}

func (x *HostStatsResponse) GetDiskTotalMib() uint64 {
	if x != nil {
		return x.DiskTotalMib
	}
	return 0
}

func (x *HostStatsResponse) GetDiskUsedMib() uint64 {
	if x != nil {
		return x.DiskUsedMib
	}
	return 0
}

func (x *HostStatsResponse) GetDiskFreeMib() uint64 {
	if x != nil {
		return x.DiskFreeMib
	}
	return 0
}

func (x *HostStatsResponse) GetVmCount() uint32 {
	if x != nil {
		return x.VmCount
	}
	return 0
}

var File_proto_axhv_proto protoreflect.FileDescriptor

const file_proto_axhv_proto_rawDesc = "" +
	"\n" +
	"\x10proto/axhv.proto\x12\x04axhv\"\a\n" +
	"\x05Empty\"\x1d\n" +
	"\vVmIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\n" +
	"VmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x13\n" +
	"\x05vm_id\x18\x03 \x01(\tR\x04vmId\"\xf3\x04\n" +
	"\x0fCreateVmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04vcpu\x18\x02 \x01(\rR\x04vcpu\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x03 \x01(\rR\tmemoryMib\x12\x1f\n" +
	"\vkernel_path\x18\x04 \x01(\tR\n" +
	"kernelPath\x12\x1f\n" +
	"\vrootfs_path\x18\x05 \x01(\tR\n" +
	"rootfsPath\x12\x1a\n" +
	"\btemplate\x18\x06 \x01(\tR\btemplate\x12 \n" +
	"\fdisk_size_gb\x18\a \x01(\rR\n" +
	"diskSizeGb\x12\x19\n" +
	"\bguest_ip\x18\b \x01(\tR\aguestIp\x12#\n" +
	"\rguest_gateway\x18\t \x01(\tR\fguestGateway\x12\x1b\n" +
	"\tboot_args\x18\n" +
	" \x01(\tR\bbootArgs\x120\n" +
	"\x14bandwidth_limit_mbps\x18\v \x01(\rR\x12bandwidthLimitMbps\x12G\n" +
	"\fport_map_tcp\x18\f \x03(\v2%.axhv.CreateVmRequest.PortMapTcpEntryR\n" +
	"portMapTcp\x12G\n" +
	"\fport_map_udp\x18\r \x03(\v2%.axhv.CreateVmRequest.PortMapUdpEntryR\n" +
	"portMapUdp\x1a=\n" +
	"\x0fPortMapTcpEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a=\n" +
	"\x0fPortMapUdpEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"C\n" +
	"\x11ResizeDiskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\vnew_size_gb\x18\x02 \x01(\rR\tnewSizeGb\"1\n" +
	"\x0fListVmsResponse\x12\x1e\n" +
	"\x03vms\x18\x01 \x03(\v2\f.axhv.VmInfoR\x03vms\"K\n" +
	"\x06VmInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x1f\n" +
	"\vsocket_path\x18\x03 \x01(\tR\n" +
	"socketPath\"\xd5\x01\n" +
	"\x0fVmStatsResponse\x12 \n" +
	"\fcpu_usage_us\x18\x01 \x01(\tR\n" +
	"cpuUsageUs\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\tR\x0fmemoryUsedBytes\x12 \n" +
	"\fnet_rx_bytes\x18\x03 \x01(\tR\n" +
	"netRxBytes\x12 \n" +
	"\fnet_tx_bytes\x18\x04 \x01(\tR\n" +
	"netTxBytes\x120\n" +
	"\x14disk_allocated_bytes\x18\x05 \x01(\tR\x12diskAllocatedBytes\"\x9c\x01\n" +
	"\x11HostStatsResponse\x12$\n" +
	"\x0edisk_total_mib\x18\x01 \x01(\x04R\fdiskTotalMib\x12\"\n" +
	"\rdisk_used_mib\x18\x02 \x01(\x04R\vdiskUsedMib\x12\"\n" +
	"\rdisk_free_mib\x18\x03 \x01(\x04R\vdiskFreeMib\x12\x19\n" +
	"\bvm_count\x18\x04 \x01(\rR\avmCount2\xb8\x04\n" +
	"\tVmService\x123\n" +
	"\bCreateVm\x12\x15.axhv.CreateVmRequest\x1a\x10.axhv.VmResponse\x12.\n" +
	"\aStartVm\x12\x11.axhv.VmIdRequest\x1a\x10.axhv.VmResponse\x12-\n" +
	"\x06StopVm\x12\x11.axhv.VmIdRequest\x1a\x10.axhv.VmResponse\x12.\n" +
	"\aPauseVm\x12\x11.axhv.VmIdRequest\x1a\x10.axhv.VmResponse\x12/\n" +
	"\bResumeVm\x12\x11.axhv.VmIdRequest\x1a\x10.axhv.VmResponse\x12/\n" +
	"\bRebootVm\x12\x11.axhv.VmIdRequest\x1a\x10.axhv.VmResponse\x12/\n" +
	"\bDeleteVm\x12\x11.axhv.VmIdRequest\x1a\x10.axhv.VmResponse\x127\n" +
	"\n" +
	"ResizeDisk\x12\x17.axhv.ResizeDiskRequest\x1a\x10.axhv.VmResponse\x12-\n" +
	"\aListVms\x12\v.axhv.Empty\x1a\x15.axhv.ListVmsResponse\x126\n" +
	"\n" +
	"GetVmStats\x12\x11.axhv.VmIdRequest\x1a\x15.axhv.VmStatsResponse\x124\n" +
	"\fGetHostStats\x12\v.axhv.Empty\x1a\x17.axhv.HostStatsResponseB!Z\x1faexon/internal/provider/axhv/pbb\x06proto3"

var (
	file_proto_axhv_proto_rawDescOnce sync.Once
	file_proto_axhv_proto_rawDescData []byte
)

func file_proto_axhv_proto_rawDescGZIP() []byte {
	file_proto_axhv_proto_rawDescOnce.Do(func() {
		file_proto_axhv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_axhv_proto_rawDesc), len(file_proto_axhv_proto_rawDesc)))
	})
	return file_proto_axhv_proto_rawDescData
}

var file_proto_axhv_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_axhv_proto_goTypes = []any{
	(*Empty)(nil),             // 0: axhv.Empty
	(*VmIdRequest)(nil),       // 1: axhv.VmIdRequest
	(*VmResponse)(nil),        // 2: axhv.VmResponse
	(*CreateVmRequest)(nil),   // 3: axhv.CreateVmRequest
	(*ResizeDiskRequest)(nil), // 4: axhv.ResizeDiskRequest
	(*ListVmsResponse)(nil),   // 5: axhv.ListVmsResponse
	(*VmInfo)(nil),            // 6: axhv.VmInfo
	(*VmStatsResponse)(nil),   // 7: axhv.VmStatsResponse
	(*HostStatsResponse)(nil), // 8: axhv.HostStatsResponse
	nil,                       // 9: axhv.CreateVmRequest.PortMapTcpEntry
	nil,                       // 10: axhv.CreateVmRequest.PortMapUdpEntry
}
var file_proto_axhv_proto_depIdxs = []int32{
	9,  // 0: axhv.CreateVmRequest.port_map_tcp:type_name -> axhv.CreateVmRequest.PortMapTcpEntry
	10, // 1: axhv.CreateVmRequest.port_map_udp:type_name -> axhv.CreateVmRequest.PortMapUdpEntry
	6,  // 2: axhv.ListVmsResponse.vms:type_name -> axhv.VmInfo
	3,  // 3: axhv.VmService.CreateVm:input_type -> axhv.CreateVmRequest
	1,  // 4: axhv.VmService.StartVm:input_type -> axhv.VmIdRequest
	1,  // 5: axhv.VmService.StopVm:input_type -> axhv.VmIdRequest
	1,  // 6: axhv.VmService.PauseVm:input_type -> axhv.VmIdRequest
	1,  // 7: axhv.VmService.ResumeVm:input_type -> axhv.VmIdRequest
	1,  // 8: axhv.VmService.RebootVm:input_type -> axhv.VmIdRequest
	1,  // 9: axhv.VmService.DeleteVm:input_type -> axhv.VmIdRequest
	4,  // 10: axhv.VmService.ResizeDisk:input_type -> axhv.ResizeDiskRequest
	0,  // 11: axhv.VmService.ListVms:input_type -> axhv.Empty
	1,  // 12: axhv.VmService.GetVmStats:input_type -> axhv.VmIdRequest
	0,  // 13: axhv.VmService.GetHostStats:input_type -> axhv.Empty
	2,  // 14: axhv.VmService.CreateVm:output_type -> axhv.VmResponse
	2,  // 15: axhv.VmService.StartVm:output_type -> axhv.VmResponse
	2,  // 16: axhv.VmService.StopVm:output_type -> axhv.VmResponse
	2,  // 17: axhv.VmService.PauseVm:output_type -> axhv.VmResponse
	2,  // 18: axhv.VmService.ResumeVm:output_type -> axhv.VmResponse
	2,  // 19: axhv.VmService.RebootVm:output_type -> axhv.VmResponse
	2,  // 20: axhv.VmService.DeleteVm:output_type -> axhv.VmResponse
	2,  // 21: axhv.VmService.ResizeDisk:output_type -> axhv.VmResponse
	5,  // 22: axhv.VmService.ListVms:output_type -> axhv.ListVmsResponse
	7,  // 23: axhv.VmService.GetVmStats:output_type -> axhv.VmStatsResponse
	8,  // 24: axhv.VmService.GetHostStats:output_type -> axhv.HostStatsResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_axhv_proto_init() }
func file_proto_axhv_proto_init() {
	if File_proto_axhv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_axhv_proto_rawDesc), len(file_proto_axhv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_axhv_proto_goTypes,
		DependencyIndexes: file_proto_axhv_proto_depIdxs,
		MessageInfos:      file_proto_axhv_proto_msgTypes,
	}.Build()
	File_proto_axhv_proto = out.File
	file_proto_axhv_proto_goTypes = nil
	file_proto_axhv_proto_depIdxs = nil
}
