// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/axhv.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VmService_CreateVm_FullMethodName     = "/axhv.VmService/CreateVm"
	VmService_StartVm_FullMethodName      = "/axhv.VmService/StartVm"
	VmService_StopVm_FullMethodName       = "/axhv.VmService/StopVm"
	VmService_PauseVm_FullMethodName      = "/axhv.VmService/PauseVm"
	VmService_ResumeVm_FullMethodName     = "/axhv.VmService/ResumeVm"
	VmService_RebootVm_FullMethodName     = "/axhv.VmService/RebootVm"
	VmService_DeleteVm_FullMethodName     = "/axhv.VmService/DeleteVm"
	VmService_ResizeDisk_FullMethodName   = "/axhv.VmService/ResizeDisk"
	VmService_ListVms_FullMethodName      = "/axhv.VmService/ListVms"
	VmService_GetVmStats_FullMethodName   = "/axhv.VmService/GetVmStats"
	VmService_GetHostStats_FullMethodName = "/axhv.VmService/GetHostStats"
)

// VmServiceClient is the client API for VmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VmServiceClient interface {
	// Lifecycle Management
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*VmResponse, error)
	StartVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error)
	StopVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error)
	PauseVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error)
	ResumeVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error)
	RebootVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error)
	DeleteVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error)
	// Resource Management
	ResizeDisk(ctx context.Context, in *ResizeDiskRequest, opts ...grpc.CallOption) (*VmResponse, error)
	// Information & Stats
	ListVms(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVmsResponse, error)
	GetVmStats(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmStatsResponse, error)
	GetHostStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostStatsResponse, error)
}

type vmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVmServiceClient(cc grpc.ClientConnInterface) VmServiceClient {
	return &vmServiceClient{cc}
}

func (c *vmServiceClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) StartVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_StartVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) StopVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_StopVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) PauseVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_PauseVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) ResumeVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_ResumeVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) RebootVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_RebootVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) DeleteVm(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_DeleteVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) ResizeDisk(ctx context.Context, in *ResizeDiskRequest, opts ...grpc.CallOption) (*VmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmResponse)
	err := c.cc.Invoke(ctx, VmService_ResizeDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) ListVms(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, VmService_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) GetVmStats(ctx context.Context, in *VmIdRequest, opts ...grpc.CallOption) (*VmStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmStatsResponse)
	err := c.cc.Invoke(ctx, VmService_GetVmStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) GetHostStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostStatsResponse)
	err := c.cc.Invoke(ctx, VmService_GetHostStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VmServiceServer is the server API for VmService service.
// All implementations must embed UnimplementedVmServiceServer
// for forward compatibility.
type VmServiceServer interface {
	// Lifecycle Management
	CreateVm(context.Context, *CreateVmRequest) (*VmResponse, error)
	StartVm(context.Context, *VmIdRequest) (*VmResponse, error)
	StopVm(context.Context, *VmIdRequest) (*VmResponse, error)
	PauseVm(context.Context, *VmIdRequest) (*VmResponse, error)
	ResumeVm(context.Context, *VmIdRequest) (*VmResponse, error)
	RebootVm(context.Context, *VmIdRequest) (*VmResponse, error)
	DeleteVm(context.Context, *VmIdRequest) (*VmResponse, error)
	// Resource Management
	ResizeDisk(context.Context, *ResizeDiskRequest) (*VmResponse, error)
	// Information & Stats
	ListVms(context.Context, *Empty) (*ListVmsResponse, error)
	GetVmStats(context.Context, *VmIdRequest) (*VmStatsResponse, error)
	GetHostStats(context.Context, *Empty) (*HostStatsResponse, error)
	mustEmbedUnimplementedVmServiceServer()
}

// UnimplementedVmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVmServiceServer struct{}

func (UnimplementedVmServiceServer) CreateVm(context.Context, *CreateVmRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedVmServiceServer) StartVm(context.Context, *VmIdRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVm not implemented")
}
func (UnimplementedVmServiceServer) StopVm(context.Context, *VmIdRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVm not implemented")
}
func (UnimplementedVmServiceServer) PauseVm(context.Context, *VmIdRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseVm not implemented")
}
func (UnimplementedVmServiceServer) ResumeVm(context.Context, *VmIdRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeVm not implemented")
}
func (UnimplementedVmServiceServer) RebootVm(context.Context, *VmIdRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebootVm not implemented")
}
func (UnimplementedVmServiceServer) DeleteVm(context.Context, *VmIdRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVm not implemented")
}
func (UnimplementedVmServiceServer) ResizeDisk(context.Context, *ResizeDiskRequest) (*VmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeDisk not implemented")
}
func (UnimplementedVmServiceServer) ListVms(context.Context, *Empty) (*ListVmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedVmServiceServer) GetVmStats(context.Context, *VmIdRequest) (*VmStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVmStats not implemented")
}
func (UnimplementedVmServiceServer) GetHostStats(context.Context, *Empty) (*HostStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostStats not implemented")
}
func (UnimplementedVmServiceServer) mustEmbedUnimplementedVmServiceServer() {}
func (UnimplementedVmServiceServer) testEmbeddedByValue()                   {}

// UnsafeVmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VmServiceServer will
// result in compilation errors.
type UnsafeVmServiceServer interface {
	mustEmbedUnimplementedVmServiceServer()
}

func RegisterVmServiceServer(s grpc.ServiceRegistrar, srv VmServiceServer) {
	// If the following call panics, it indicates UnimplementedVmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VmService_ServiceDesc, srv)
}

func _VmService_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_StartVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).StartVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_StartVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).StartVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_StopVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).StopVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_StopVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).StopVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_PauseVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).PauseVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_PauseVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).PauseVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_ResumeVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).ResumeVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_ResumeVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).ResumeVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_RebootVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).RebootVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_RebootVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).RebootVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_DeleteVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).DeleteVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_DeleteVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).DeleteVm(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_ResizeDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).ResizeDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_ResizeDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).ResizeDisk(ctx, req.(*ResizeDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).ListVms(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_GetVmStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).GetVmStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_GetVmStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).GetVmStats(ctx, req.(*VmIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_GetHostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).GetHostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VmService_GetHostStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).GetHostStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VmService_ServiceDesc is the grpc.ServiceDesc for VmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axhv.VmService",
	HandlerType: (*VmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _VmService_CreateVm_Handler,
		},
		{
			MethodName: "StartVm",
			Handler:    _VmService_StartVm_Handler,
		},
		{
			MethodName: "StopVm",
			Handler:    _VmService_StopVm_Handler,
		},
		{
			MethodName: "PauseVm",
			Handler:    _VmService_PauseVm_Handler,
		},
		{
			MethodName: "ResumeVm",
			Handler:    _VmService_ResumeVm_Handler,
		},
		{
			MethodName: "RebootVm",
			Handler:    _VmService_RebootVm_Handler,
		},
		{
			MethodName: "DeleteVm",
			Handler:    _VmService_DeleteVm_Handler,
		},
		{
			MethodName: "ResizeDisk",
			Handler:    _VmService_ResizeDisk_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _VmService_ListVms_Handler,
		},
		{
			MethodName: "GetVmStats",
			Handler:    _VmService_GetVmStats_Handler,
		},
		{
			MethodName: "GetHostStats",
			Handler:    _VmService_GetHostStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/axhv.proto",
}
